name: fconsole
description: A overlay console log list like v-console.
version: 2.2.1
homepage: https://github.com/fluttercandies/fconsole

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # device_info_plus: ^3.2.4
  device_info_plus: # 9.1.0 
    git:
      url: "https://gitee.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/device_info_plus/device_info_plus"
  intl: ^0.17.0
  tapped: ^2.0.0
  animations: ^2.0.0
  left_scroll_actions: ^2.0.0
  # share_plus: ^4.0.7
  share_plus: # 7.2.0 
    git:
      url: "https://gitee.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/share_plus/share_plus"
  json_view: ^0.4.0

dependency_overrides:
 url_launcher: # 4.0.0
   git:
     url: "https://gitee.com/openharmony-sig/flutter_packages.git"
     path: "packages/url_launcher/url_launcher"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
